# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
