# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_v1', '0002_auto_20180619_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源标题')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='资源链接')),
                ('passwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='资源密码')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='写入时间')),
            ],
            options={
                'verbose_name_plural': '电影资源',
                'ordering': ['-insert_date'],
                'verbose_name': '电影资源',
            },
        ),
    ]
